version: "3.8"
services:
  fastapi:
    build: .
    container_name: neo-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - JWT_SUPER_SECRET=${JWT_SUPER_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    # If you require a password, use command or a redis.conf to enable it:
    # command: redis-server --requirepass ${REDIS_PASSWORD}