postgres:
  host: ${oc.env:POSTGRES_HOST}
  port: ${oc.env:POSTGRES_PORT}
  user: ${oc.env:POSTGRES_USER}
  password: ${oc.env:POSTGRES_PASSWORD}
  database: ${oc.env:POSTGRES_DATABASE}

jwt_auth:
  super_secret_key: ${oc.env:JWT_SUPER_SECRET}
  refresh_secret_key: ${oc.env:JWT_REFRESH_SECRET}

redis:
  host: ${oc.env:REDIS_HOST, "localhost"}
  port: ${oc.env:REDIS_PORT, "6379"}
  password: ${oc.env:REDIS_PASSWORD, ""}

smtp:
  smtp_server: ${oc.env:SMTP_SERVER, "smtp.gmail.com"}
  smtp_port: ${oc.env:SMTP_PORT, 587}
  username: ${oc.env:SMTP_USER_NAME}
  password: ${oc.env:SMTP_PASSWORD}
  use_tls: ${oc.env:SMTP_USE_TLS, true}
  max_retries: ${oc.env:SMTP_MAX_RETRIES, 3}
